development:
  adapter: postgresql
  encoding: unicode
  database: p_flo_development
  pool: 5
  reaping_frequency: 10
  host: localhost
  port: 5432
staging:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] %>
  pool: 5
  reaping_frequency: 10
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: 5432
production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] %>
  pool: 5
  reaping_frequency: 10
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: 5432
test:
  adapter: postgresql
  encoding: unicode
  database: p_flo_test
  pool: 5
  reaping_frequency: 10
  host: localhost
  port: 5432
