amazon:
  access_key: <%= ENV['AWS_KEY'] %>
  secret_key: <%= ENV['AWS_SECRET'] %>
  bucket: <%= ENV['BUCKET_NAME'] %>
  app_bucket: <%= ENV['APP_BUCKET_NAME'] %>
stripe:
  client_id: <%= ENV['STRIPE_CONNECT_CLIENT_ID'] %>
  secret: <%= ENV['STRIPE_SECRET'] %>
  test_account: 000123456789
  test_bsb: 110000000
  default_currency: "aud"
bitly:
  host: "https://positivflo-staging.herokuapp.com"
twilio:
  sid: <%= ENV['TWILIO_ID'] %>
  token: <%= ENV['TWILIO_TOKEN'] %>
  number: <%= ENV['TWILIO_NUMBER'] %>
main_host: https://positivflo-staging.herokuapp.com
fees:
  shipping: 0
  trainer: 150
  trainer_percent: 0.03
  client_percent: 0.0095
  gst_percent: 0.10
  stripe: 30
  pflo_trans_fee: 25
